services:
  database:
    image: mysql:9.5.0
    container_name: lineage-lens-database
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DATABASE_PORT}:3306"

volumes:
  mysql_data: